# Generated by Django 5.1.5 on 2025-01-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_remove_contact_created_at_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('url', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
